Add go modules & circleCI orb
Financial-Times/annotations-monitoring-service pull request #15
Opened 2020-10-27 14:25 UTC by georgi-denchew

# Description

## What

Migrate to go modules and use the circleCI orb

## Scope and particulars of this PR (Please tick all that apply)

- [x] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2020-10-30 07:58 UTC, ivan-p-nikolov commented on .circleci/config.yml
> +      - ft-golang-ci/docker-build:
Shouldn't we add `dockerhub-shared` context

2020-10-30 07:58 UTC, ivan-p-nikolov commented on go.mod
> +go 1.14
I think you need to update your local golang version. The current one is 1.15. 
And It's fine to keep 1.14 in here.

2020-11-02 14:23 UTC, mchompalova requested changes

2020-11-02 14:23 UTC, mchompalova commented on README.md
> +        go test -race ./...
We should add -mod=readonly here

2020-11-05 11:54 UTC, mchompalova commented on .circleci/config.yml
> +      - ft-golang-ci/docker-build:
It's not necessary anymore.

2020-11-05 12:21 UTC, mchompalova submitted a review, later dismissed

2020-11-19 14:23 UTC, ekaneva commented
@georgi-denchew
Metadata marked this service as one that is going to be decommissioned soon in [the service list](https://docs.google.com/spreadsheets/d/1_r7biMVRIxUMEwAviQP4iAFbMTvQWbWGzdY2BNbLfgY/edit#gid=847291464), so I think it is better to close this PR?

2021-12-10 08:14 UTC, martin-stanchev approved these changes

2021-12-10 08:14 UTC, dtvalk-ov approved these changes

2021-12-10 08:22 UTC, merged